### ISSUE TITLE
Permissions ByPass

### ISSUE THREAD

**Issue by ghost** [WetABQ/Nukkit-AntiCheat#1]
Can you add permissions for bypass anti-cheat?

**Comment by WetABQ** [comment]
I will not be able to maintain this plugin anymore

**Comment by ghost** [comment]
@WetABQ Oke, i understood. But can you replace Runabble with Repeating Delayed Tasks? It's more efficient on RAM. Runnable consume so much ram bro..

**Comment by WetABQ** [comment]
I will consider using AsycTask.
But I will not place them in the main thread.

**Comment by WetABQ** [comment]
Update to WAC
